
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://106.12.124.234:3306/lark?charSet=UTF-8
    username: lark
    password: "lark"

    #连接池配置 hikari数据源配置
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 30000
      max-lifetime: 1800000
      maximum-pool-size: 20
      connection-test-query: SELECT 1 FROM DUAL



eureka:
  client:
    serviceUrl:
      defaultZone: http://106.12.124.234:8761/eureka/
  instance:
    prefer-ip-address: true
    instanceId: ${spring.application.name}:${random.value}

